about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Themefisher"
contact_form_action = "#"
copyright = "Copyright by your company"
custom_script = ""
description = "This is meta description"
email = ""
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+211234565523"
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
theme_copyright = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Hacker, Website Developer, and recently started your 3 businesses."
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to Mukund Kadu Blogs"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = true
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/mukunda.kadu.5"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/mikki_virus"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/mikki_virus/"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "https://github.com/mikkivirus-dev"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/mukund-kadu/"
title = "linkedin"
